name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  # build:
  #
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          mkdir -p ./pkg/testdata/emptydir
          go test -covermode=count -coverprofile "coverage.out" ./...

      - name: Cover
        run: go tool cover -func=coverage.out
