name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  # build:
  #
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Test *.go-sources with cover
        run: |
          mkdir -p ./pkg/testdata/emptydir
          go get -v -d $GITHUB_WORKSPACE/..
          go test -covermode=count -coverprofile "coverage.out" $GITHUB_WORKSPACE/..
          go tool cover -func=coverage.out
