name: "Go - Build and Test"

on:
  push:
    paths: ['**.go']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          mkdir -p ./pkg/testdata/emptydir
          go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Upload coverage to Codecov
        run:
          bash <(curl -s https://codecov.io/bash)
      #
      # - name: Cover
      #   run: |
      #     go tool cover -func=coverage.out
